<div class='side'>
    <h2><span>Kategori</span></h2>
    <!--  Kategori -->
    <ul id='vmenu' class='sidenav' style='overflow: auto;height: 600px;'>
    </ul> 
</div>
<div class='side2'>
    <h2><span>Status Lahan</span></h2>
    <!--  Kategori -->
    <ul id='vmenux' class='sidenav'>
        <li><input type='checkbox' id='status1' name='status1' value='1'/><label for='status1'>Lahan Kas Desa</label></li><li><input type='checkbox' id='status2' name='status2' value='2'/><label for='status2'>Tanah Negara</label></li><li><input type='checkbox' id='status3' name='status3' value='3'/><label for='status3'>HGU</label></li><li><input type='checkbox' id='status4' name='status4' value='4'/><label for='status4'>Perhutani</label></li><li><input type='checkbox' id='status5' name='status5' value='5'/><label for='status5'>BKSDA</label></li><li><input type='checkbox' id='status6' name='status6' value='6'/><label for='status6'>Hak Milik</label></li><li><input type='checkbox' id='status7' name='status7' value='7'/><label for='status7'>Tanah Adat</label></li><li><input type='checkbox' id='status8' name='status8' value='8'/><label for='status8'>Lahan Potensial</label></li>                      
    </ul> 
</div>
<div class='side3'>
    <h2><span>Tata Guna Lahan</span></h2>
    <!--  Kategori -->
    <ul id='vmenum' class='sidenav'>
        <li><input type='checkbox' id='tata1' name='tata1' value='1'/><label for='tata1'>Permukiman</label><span class='ttg' style='clear:both;background-color:#820D1B;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li><li><input type='checkbox' id='tata2' name='tata2' value='2'/><label for='tata2'>Sawah</label><span class='ttg' style='clear:both;background-color:#69FF12;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li><li><input type='checkbox' id='tata3' name='tata3' value='3'/><label for='tata3'>Pertanian Non Sawah</label><span class='ttg' style='clear:both;background-color:#B5B016;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li><li><input type='checkbox' id='tata4' name='tata4' value='4'/><label for='tata4'>Industri</label><span class='ttg' style='clear:both;background-color:#2411F2;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li><li><input type='checkbox' id='tata5' name='tata5' value='5'/><label for='tata5'>Fasum Fasos</label><span class='ttg' style='clear:both;background-color:#525137;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li><li><input type='checkbox' id='tata6' name='tata6' value='6'/><label for='tata6'>Hutan</label><span class='ttg' style='clear:both;background-color:#7A7709;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li><li><input type='checkbox' id='tata7' name='tata7' value='7'/><label for='tata7'>Kebun Campuran</label><span class='ttg' style='clear:both;background-color:#F5F293;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li><li><input type='checkbox' id='tata8' name='tata8' value='8'/><label for='tata8'>Perkebunan</label><span class='ttg' style='clear:both;background-color:#858479;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li><li><input type='checkbox' id='tata9' name='tata9' value='9'/><label for='tata9'>Pusat Perdagangan</label><span class='ttg' style='clear:both;background-color:#BA4C07;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li><li><input type='checkbox' id='tata10' name='tata10' value='10'/><label for='tata10'>Kolam</label><span class='ttg' style='clear:both;background-color:#48CBF0;border-radius: 50%;width: 20px;height: 20px; padding:8px;border:2px solid #fff;'></span></li>                      
    </ul> 
</div>